services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: stelsey
      POSTGRES_USER: stelsey
      POSTGRES_PASSWORD: stelsey
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: